# -*- coding: utf-8 -*-
"""
Created on Fri Jul 18 11:58:03 2025

@author: Paul

Script to create Figure 8 in the paper "The role of coupling and
timescales for interacting tipping elements"
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
import matplotlib as mpl
import matplotlib.colors as colors

def f(x, forcing):
    """
    Generic double fold bifurcation model used for both upstream and downstream
    systems.

    Parameters
    ----------
    x : float64
        State variable for upstream or downstream system.
    forcing : float64
        External forcing to drive the system.

    Returns
    -------
    f : float64
        RHS of ODE.

    """  
    f = 3*x - x**3 + forcing    
    return (f)

def forcing_ramp(t, lamb_min, lamb_max, r):
    """
    Tanh ramp forcing for upstream system.

    Parameters
    ----------
    t : float64
        Time
    lamb_min : float64
        Initial level of forcing.
    lamb_max : float64
        Final level of forcing.
    r : float64
        Rate parameter of ramp.

    Returns
    -------
    lamb : float64
        Upstream ramp forcing profile.

    """
    lamb = lamb_min + (lamb_max-lamb_min)*(np.tanh(r*t)+1)/2   
    return (lamb)


def forcing_loc(x, a, b, c, d):
    """
    Localised state coupling from upstream to downstream.

    Parameters
    ----------
    x : float64
        State variable of upstream system.
    a : float64
        Initial level of forcing.
    b : float64
        Amplitude of forcing.
    c : float64
        DESCRIPTION.
    d : float64
        Offset coupling parameter.

    Returns
    -------
    loc : float64
        Localised state downstream overshoot forcing profile.

    """   
    loc = a + b/np.cosh(c*(x - d))
    
    return (loc)

def truncate_colormap(cmap, minval=0.0, maxval=1.0, n=100):
    new_cmap = colors.LinearSegmentedColormap.from_list(
        'trunc({n},{a:.2f},{b:.2f})'.format(n=cmap.name, a=minval, b=maxval),
        cmap(np.linspace(minval, maxval, n)))
    return new_cmap

fontsize = 10
rc('font', **{'size' : fontsize})
rc('text', usetex=True)

# Time parameters
tstart = -55                        # Start time
tend = 50                           # End time
dt = 0.0005                         # Spacing between time intervals
n = int((tend - tstart)/dt)         # Number of time intervals
t = np.linspace(tstart, tend, n+1)  # Time values
burn = 5                            # Burn time length to remove any transient behaviour
burn_pts = int(burn/dt)             # Number of points in burn period

# System parameter
epsilon = 0.05      # Timescale separation

# Upstream forcing parameters
lamb_min = 0                # Start level of upstream forcing
lamb_max = 4                # End level of upstream forcing 
r = 0.05                    # Rate parameter of upstream forcing
xeq_start = -np.sqrt(3)     # Starting equilibrium for upstream systeml

# Downstream forcing parameters
a = 0               # Start level of downstream forcing
c = 2               # Inv. prop. to overshoot period of downstream forcing
d = 0.5             # Offset for coupling of downstream forcing during tipping of upstream 

# Array of different coupling amplitudes b
bs_loc = [1.8, 2.0, 2.2115194, 2.2115195, 8, 27.4, 29.3, 40]

# Initialise figure
fig, ax = plt.subplots(3,3,sharex=True,figsize=(7.007874,6))

ax[2,2].set_xlim(-2.5,5)
ax[2,2].set_ylim(1,300)
ax[2,2].set_yscale('log')

ax[0,0].set_ylim(-2,4)
ax[0,1].set_ylim(-2,4)
ax[0,2].set_ylim(-2,4)
ax[1,0].set_ylim(-2,4)
ax[1,1].set_ylim(-2,4)
ax[1,2].set_ylim(-2,4)
ax[2,0].set_ylim(-2,4)
ax[2,1].set_ylim(-2,4)

ax[0,0].set_xticks([-2,0,2,4])

ax[2,0].set_xlabel(r'$\lambda$')
ax[2,1].set_xlabel(r'$\lambda$')
ax[2,2].set_xlabel(r'$\lambda$')

ax[0,0].set_ylabel('y')
ax[0,1].set_ylabel('y')
ax[0,2].set_ylabel('y')
ax[1,0].set_ylabel('y')
ax[1,1].set_ylabel('y')
ax[1,2].set_ylabel('y')
ax[2,0].set_ylabel('y')
ax[2,1].set_ylabel('y')
ax[2,2].set_ylabel('b')

# Load in 2 parameter bifurcation data (generated by XPPAut)
data = np.genfromtxt('Cascade_loc_coupling_2par_lambda_b_v1.dat', dtype=float, delimiter=' ')
data2 = np.genfromtxt('Cascade_loc_coupling_2par_lambda_b_v2.dat', dtype=float, delimiter=' ')
lamb=data[:,0]
b=data[:,1]
lamb2=data2[:,0]
b2=data2[:,1]

# Plotting 2 parameter bifurcation
ax[2,2].plot(lamb,b,c='b',lw=1)
ax[2,2].plot(lamb2,b2,c='b',lw=1)

idx = np.argmin(lamb)
ax[2,2].plot([-2,-2],[0,b[idx]],c='b',lw=2)
ax[2,2].plot([-2,-2],[b[idx],300],c='b',lw=1)

idx2 = np.argmax(lamb2)
ax[2,2].plot([2,2],[0,b2[idx2]],c='b',lw=2)
ax[2,2].plot([2,2],[b2[idx2],300],c='b',lw=1)

ax[2,2].fill_between(np.linspace(0,4,1001),0,300,facecolor='k',edgecolor='none',alpha=0.2)

# List of colours for plotting
colours = ['Blues_r','Oranges_r','Greens_r','Reds_r','Purples_r','pink','bone','RdPu_r']

# Set bounds (in log space) for colour intervals of different system speeds
bounds = [-7,-4,-2,-1]

for i in range(len(bs_loc)):
    cmap = truncate_colormap(plt.get_cmap(colours[i]), minval=0.2, maxval=0.7, n=100)
    norm = mpl.colors.BoundaryNorm(bounds, cmap.N)
    ax[2,2].plot([-5,5],[bs_loc[i],bs_loc[i]],ls='--',lw=1,c=cmap(norm(-6)))

# Set axes bounds 
lam_low_loc = -2.5
lam_high_loc = 5
x_high_loc = 4
y_high_loc = 4.5

# Locations of arrows to plot
larrowvectors = [[1.1,3.6], [1.1,3.6], [1.1,3.6], [1.1,2.3,3.6], [1.1,2.2,3.6], [1.1,2,3.6], [1.1,2,3.6], [1.1,1.7,3.6]]
yarrowvectors = [[-1.6,-1.7], [-1.6,-1.7], [-1.6,-1.7], [-1.6,0.8,2], [-1.6,0.9,2], [-1.6,0.9,2], [-1.6,0.9,2], [-1.6,0.9,2]]

text_kwargs = dict(ha='center', va='center', fontsize=fontsize)

# Loop over the different coupling amplitudes b
for j in range(len(bs_loc)):
    # Initialise variables 
    x_det = np.zeros(n+1)     
    y_det_loc = np.zeros(n+1)
    speed = np.zeros(n+1)
    
    # Initialise start points for variables
    x_det[0] = xeq_start
    y_det_loc[0] = xeq_start
    
    # Calculate deterministic trajectories
    for i in range(n):
        x_det[i+1] = x_det[i] + dt*f(x_det[i], forcing_ramp(t[i], lamb_min, lamb_max, r))
        y_det_loc[i+1] = y_det_loc[i] + dt*f(y_det_loc[i], forcing_loc(x_det[i], a, bs_loc[j], c, d))/epsilon
        speed[i+1] = np.sqrt((x_det[i+1]-x_det[i])**2 + (y_det_loc[i+1]-y_det_loc[i])**2)
        
   
    ## Equilibria for localsied coupling
    yeq = np.linspace(-2,4,100001)
    yeq2 = np.linspace(-2,4,100001)
    xeq = np.arccosh(bs_loc[j]/((yeq**3)-(3*yeq)-a))/c + d
    xeq2 = -np.arccosh(bs_loc[j]/((yeq2**3)-(3*yeq2)-a))/c + d
    lambdaeq = (xeq**3) - (3*xeq)
    lambdaeq2 = (xeq2**3) - (3*xeq2)    

    lambdaeq[lambdaeq<lam_low_loc], xeq[lambdaeq<lam_low_loc], yeq[lambdaeq<lam_low_loc] = np.nan, np.nan, np.nan
    lambdaeq[lambdaeq>lam_high_loc], xeq[lambdaeq>lam_high_loc], yeq[lambdaeq>lam_high_loc] = np.nan, np.nan, np.nan
    lambdaeq[xeq>x_high_loc], xeq[xeq>x_high_loc], yeq[xeq>x_high_loc] = np.nan, np.nan, np.nan
    lambdaeq[yeq>y_high_loc], xeq[yeq>y_high_loc], yeq[yeq>y_high_loc] = np.nan, np.nan, np.nan
    lambdaeq2[lambdaeq2<lam_low_loc], xeq2[lambdaeq2<lam_low_loc], yeq2[lambdaeq2<lam_low_loc] = np.nan, np.nan, np.nan
    lambdaeq2[lambdaeq2>lam_high_loc], xeq2[lambdaeq2>lam_high_loc], yeq2[lambdaeq2>lam_high_loc] = np.nan, np.nan, np.nan
    lambdaeq2[xeq2>x_high_loc], xeq2[xeq2>x_high_loc], yeq2[xeq2>x_high_loc] = np.nan, np.nan, np.nan
    lambdaeq2[yeq2>y_high_loc], xeq2[yeq2>y_high_loc], yeq2[yeq2>y_high_loc] = np.nan, np.nan, np.nan        
    
    # Plotting equilibria
    ax[int((j)/3),(j)%3].plot(lambdaeq,yeq,c='k',ls='--',lw=1)
    ax[int((j)/3),(j)%3].plot(lambdaeq[(3-3*(xeq**2)<0)&(3-3*(yeq**2)<0)],yeq[(3-3*(xeq**2)<0)&(3-3*(yeq**2)<0)],c='k',lw=1)
    ax[int((j)/3),(j)%3].plot(lambdaeq2,yeq2,c='k',ls='--',lw=1)
    ax[int((j)/3),(j)%3].plot(lambdaeq2[(3-3*(xeq2**2)<0)&(3-3*(yeq2**2)<0)],yeq2[(3-3*(xeq2**2)<0)&(3-3*(yeq2**2)<0)],c='k',lw=1)

    # Plotting system trajectory
    cmap = truncate_colormap(plt.get_cmap(colours[j]), minval=0.2, maxval=0.7, n=100)
    norm = mpl.colors.BoundaryNorm(bounds, cmap.N)
    ax[int((j)/3),(j)%3].scatter(forcing_ramp(t[t>=-50], lamb_min, lamb_max, r),y_det_loc[t>=-50],c=np.log10(speed[t>=-50]),cmap=cmap,norm=norm,s=0.3,zorder=20, rasterized=True)#lw=2)

    # Add arrow(s) to trajectory
    larrow = larrowvectors[j]
    yarrow = yarrowvectors[j]
    for k in range(len(larrow)):
        idx = np.nanargmin(np.abs(forcing_ramp(t, lamb_min, lamb_max, r) - larrow[k])+np.abs(y_det_loc - yarrow[k]))
        arrow0 = forcing_ramp(t[idx+1], lamb_min, lamb_max, r), y_det_loc[idx+1]
        arrow1 = forcing_ramp(t[idx], lamb_min, lamb_max, r), y_det_loc[idx]
        ax[int((j)/3),(j)%3].annotate('',xytext=(arrow1),xy=(arrow0),arrowprops=dict(arrowstyle="simple", color=cmap(norm(np.log10(speed[idx])))),size=11)
    
    ax[int((j)/3),(j)%3].text(0.5, 1.08, '$b$ = '+str(bs_loc[j]), transform=ax[int((j)/3),(j)%3].transAxes, **text_kwargs)
    

ax[0,0].text(-0.2, 1.12, '\\textbf{(a)}', transform=ax[0,0].transAxes, **text_kwargs)
ax[0,1].text(-0.2, 1.12, '\\textbf{(b)}', transform=ax[0,1].transAxes, **text_kwargs)
ax[0,2].text(-0.2, 1.12, '\\textbf{(c)}', transform=ax[0,2].transAxes, **text_kwargs)
ax[1,0].text(-0.2, 1.12, '\\textbf{(d)}', transform=ax[1,0].transAxes, **text_kwargs)
ax[1,1].text(-0.2, 1.12, '\\textbf{(e)}', transform=ax[1,1].transAxes, **text_kwargs)
ax[1,2].text(-0.2, 1.12, '\\textbf{(f)}', transform=ax[1,2].transAxes, **text_kwargs)
ax[2,0].text(-0.2, 1.12, '\\textbf{(g)}', transform=ax[2,0].transAxes, **text_kwargs)
ax[2,1].text(-0.2, 1.12, '\\textbf{(h)}', transform=ax[2,1].transAxes, **text_kwargs)
ax[2,2].text(-0.2, 1.12, '\\textbf{(i)}', transform=ax[2,2].transAxes, **text_kwargs)

sns.despine()
fig.subplots_adjust(top=0.94,bottom=0.07,left=0.07,right=0.987,hspace=0.275,wspace=0.325)

# fig.savefig('../Figures/Localised_coupling/Cascade_tipping_loc_coupling_2par_lambda_y_bif_diags_arrows_speed_v2.pdf', format='pdf', dpi=800)

